version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    container_name: xkcd_postgres
    restart: always
    environment:
      POSTGRES_USER: xkcd_user
      POSTGRES_PASSWORD: xkcd_pass
      POSTGRES_DB: xkcd_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
